spring:
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jira:
  api:
    baseUrl: ${BASE_URL}
    username: ${JIRA_USERNAME}
    password: ${JIRA_PASSWORD}


